default_platform(:ios)

platform :ios do
  desc "Build and upload a release build to TestFlight."
  lane :testflight_release do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID", ""),
      issuer_id: ENV.fetch("ASC_ISSUER_ID", ""),
      key_content: ENV.fetch("ASC_KEY_CONTENT", ""),
      is_key_content_base64: true
    )

    build_app(
      scheme: "Enchanted",
      xcodeproj: "Enchanted.xcodeproj",
      export_method: "app-store",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
